// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whrtmdoktihsctssdyjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndocnRtZG9rdGloc2N0c3NkeWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODA5MDEsImV4cCI6MjA2NzA1NjkwMX0.VZIZzfcL0hybiNZxinHjsOsChiuNckYRX-bj_p-T6Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});